C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\Rail-Static 1
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\Rail-Static 1
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\Rail-Static 1
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-Static 1
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-Static 1
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\Rail-Static 1
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-Solid box-20g-downwards
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-Solidbox-40g-left
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-solidbox-40g-forward
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-solidbox-40g-forward
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-solidbox-40g-backwards
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-solidbox-40g-backwards
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-Solidbox-40g-left
C:\Users\Axiom\Documents\GitHub\ARCHIBALD-the-battery-box\new.16-17\BOX4simulatingmount2chassis-Solid box-20g-downwards
c:\users\axiom\appdata\local\temp\Assem1-Static 1
